; AOWIS Server GUI configuration
; Edit this file in the deployed webroot, then reload the page.

[gui]
examples_builtin_enable=true
map_wasm_renderer=rhi

[map_server]
base_url=
api_key=
delete_api_key=

[shortcuts]
fullscreen=F11
map_editor_add_customer_point=4
map_editor_add_junction=2
map_editor_add_note=9
map_editor_add_pipe=1
map_editor_add_power_source=7
map_editor_add_pump=5
map_editor_add_reservoir=8
map_editor_add_tank=6
map_editor_add_valve=3
map_editor_delete=Del
map_editor_select=Esc
map_pan_down=I
map_pan_left=U
map_pan_right=A
map_pan_up=V
map_provider_arcgis_sat=F1
map_provider_cycloosm=F4
map_provider_openstreetmap=F2
map_provider_opentopomap=F3
map_zoom_in=L
map_zoom_out=X
sidebar_toggle=Win+Tab
simulation_run=Ctrl+R
simulation_run_alternate=Shift+Enter
