if(NOT DEFINED AOWIS_SOURCE_DIR OR AOWIS_SOURCE_DIR STREQUAL "")
    message(FATAL_ERROR "AOWIS_SOURCE_DIR is required")
endif()

if(NOT DEFINED AOWIS_OUTPUT_FILE OR AOWIS_OUTPUT_FILE STREQUAL "")
    message(FATAL_ERROR "AOWIS_OUTPUT_FILE is required")
endif()

file(GLOB_RECURSE AOWIS_GUI_FINGERPRINT_FILES
    LIST_DIRECTORIES FALSE
    "${AOWIS_SOURCE_DIR}/src/*.cpp"
    "${AOWIS_SOURCE_DIR}/src/*.h"
)

list(APPEND AOWIS_GUI_FINGERPRINT_FILES
    "${AOWIS_SOURCE_DIR}/CMakeLists.txt"
    "${AOWIS_SOURCE_DIR}/resources.qrc"
)
list(REMOVE_DUPLICATES AOWIS_GUI_FINGERPRINT_FILES)
list(SORT AOWIS_GUI_FINGERPRINT_FILES)

set(AOWIS_FINGERPRINT_INPUT "")
foreach(AOWIS_FILE IN LISTS AOWIS_GUI_FINGERPRINT_FILES)
    if(NOT EXISTS "${AOWIS_FILE}")
        continue()
    endif()

    file(SHA256 "${AOWIS_FILE}" AOWIS_FILE_HASH)
    file(RELATIVE_PATH AOWIS_RELATIVE_FILE "${AOWIS_SOURCE_DIR}" "${AOWIS_FILE}")
    string(APPEND AOWIS_FINGERPRINT_INPUT "${AOWIS_RELATIVE_FILE}:${AOWIS_FILE_HASH}\n")
endforeach()

string(SHA256 AOWIS_SOURCE_FINGERPRINT "${AOWIS_FINGERPRINT_INPUT}")
set(AOWIS_HEADER_CONTENT
    "#pragma once\n#define AOWIS_GUI_SOURCE_FINGERPRINT \"${AOWIS_SOURCE_FINGERPRINT}\"\n")

get_filename_component(AOWIS_OUTPUT_DIRECTORY "${AOWIS_OUTPUT_FILE}" DIRECTORY)
file(MAKE_DIRECTORY "${AOWIS_OUTPUT_DIRECTORY}")

set(AOWIS_EXISTING_CONTENT "")
if(EXISTS "${AOWIS_OUTPUT_FILE}")
    file(READ "${AOWIS_OUTPUT_FILE}" AOWIS_EXISTING_CONTENT)
endif()

if(NOT AOWIS_EXISTING_CONTENT STREQUAL AOWIS_HEADER_CONTENT)
    file(WRITE "${AOWIS_OUTPUT_FILE}" "${AOWIS_HEADER_CONTENT}")
    message(STATUS "AOWIS GUI source content changed; refreshing build fingerprint")
endif()
